plugins {
  id 'java-library'
  // Java module - no additional plugin needed
}

 
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
dependencies {
   implementation 'androidx.annotation:annotation:1.7.0'
   val analysisApiKotlinVersion = "2.2.20-dev-2432" // 13-May-2025 (version that KSP uses)
    api("org.jetbrains.kotlin:kotlin-compiler:$analysisApiKotlinVersion")
    api project(':java-stubs') 
    implementation("org.jetbrains.intellij.deps:trove4j:1.0.20200330")
}